### ISSUE TITLE
Dummy WIndow not working

### ISSUE THREAD

**Issue by MacedoMMLS** [lyckantropen/moonlight_hdr_launcher#13]
The new feature is not creating the new dummy window. It does not even appear on the log.

**Comment by lyckantropen** [comment]
My bad indeed. I made it work only with `remote_desktop=1`. Will fix.

**Comment by lyckantropen** [comment]
Fixed in 425e26e

**Comment by MacedoMMLS** [comment]
Thx. Working perfectly now.
