### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Maz111111** [lyckantropen/moonlight_hdr_launcher#17]
I'd like to uninstall in win11 but there is no uninstaller. 

While there are registry changes (like it is said in the description) it should be not enough to just delete the folder in Programme files.

Best regards

**Comment by lyckantropen** [comment]
Hi. Since more people were asking I'll add an option in the installer to
remove.

wt., 21 cze 2022, 06:11 użytkownik Maz111111 ***@***.***>
napisał:

**Comment by lyckantropen** [comment]
Release [1.2.0](https://github.com/lyckantropen/moonlight_hdr_launcher/releases/tag/v1.2.0) adds an uninstall option to the installer ([d8612eb](https://github.com/lyckantropen/moonlight_hdr_launcher/commit/d8612eb9f6e2b5ab9082d4c9673e1eb2bdf5e64c)). Apologies for taking a longer time.
