### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by fidoboy** [lyckantropen/moonlight_hdr_launcher#21]
How can be uninstalled this software?

**Comment by RunAway189** [comment]
I'd like to know the same. Please help

**Comment by lyckantropen** [comment]
Release [1.2.0](https://github.com/lyckantropen/moonlight_hdr_launcher/releases/tag/v1.2.0) adds an uninstall option to the installer ([d8612eb](https://github.com/lyckantropen/moonlight_hdr_launcher/commit/d8612eb9f6e2b5ab9082d4c9673e1eb2bdf5e64c)). Apologies for taking a longer time.
