### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by RunAway189** [lyckantropen/moonlight_hdr_launcher#23]
I'd like to uninstall the launcher. How I can do it? Even manually would be fine

**Comment by lyckantropen** [comment]
Release [1.2.0](https://github.com/lyckantropen/moonlight_hdr_launcher/releases/tag/v1.2.0) adds an uninstall option to the installer ([d8612eb](https://github.com/lyckantropen/moonlight_hdr_launcher/commit/d8612eb9f6e2b5ab9082d4c9673e1eb2bdf5e64c)). Apologies for taking a longer time.
