### ISSUE TITLE
New Steam Big Picture Mode

### ISSUE THREAD

**Issue by JunaidDawood** [lyckantropen/moonlight_hdr_launcher#24]
With the update that includes the new Big Picture mode for Steam, can you update the HDR launcher to launch this? Thank you.

Also, side note what does native resolution refer to? The resolution of the PC's monitor or the resolution of the display I'm streaming to?

**Comment by lyckantropen** [comment]
Sure, if someone tells me the new command line for the new Big Picture. I couldn't find it. You can edit it yourself in the .ini if you manage to figure it out.

The native resolution refers to the resolution that the PC is running at the time of installation.

**Comment by JunaidDawood** [comment]
I managed to figure it out: "Steam\steam.exe -start steam://open/bigpicture". Thank you for your help in resolving this.
