### ISSUE TITLE
HDR not toggling on on TV

### ISSUE THREAD

**Issue by sbernier1** [lyckantropen/moonlight_hdr_launcher#4]
Hi,

I followed the HDTV & HDR monitor owners configuration since my monitor supports HDR.
When I launch SteamOS icon in moonlight it launches the gamestream_launchpad exe and toggles on HDR in Windows.

But my TV still won't display HDR. I added log files which might help. My host PC has a RTX 3080 (with latest geforce experience since it was bugged before) and my client has a GT 1030 (HDMI 2.0 so should work fine, I can have 4k@60fps). I have moonlight installed on a linux machine. In moonlight settings I have selected HEVC and I don't get any errors on startup.

Thank you.

[moonlight_hdr_launcher_log.txt](https://github.com/lyckantropen/moonlight_hdr_launcher/files/5925957/moonlight_hdr_launcher_log.txt)

[NvStreamerCurrent.log](https://github.com/lyckantropen/moonlight_hdr_launcher/files/5925954/NvStreamerCurrent.log)

**Comment by sbernier1** [comment]
I noticed that i'm supposed to be able to toggle a HDR support option in moonlight but I can't find it. Is it because Linux does not support HDR? ....

**Comment by sbernier1** [comment]
if it is not possible to use HDR on linux, could it be possible to install an android VM with gpu passthrough (is that even possible? do nvidia drivers work on android?) and use HDR?

**Comment by lyckantropen** [comment]
Sorry for delayed response. Sadly I haven't tested this on Linux as a client. I would assume that the client operating system (in this case I assume this is the display server - XOrg or Wayland, depending on your case) needs to support HDR to work with HDR streaming. This is more of a question regarding Moonlight than the HDR hack.

**Comment by Josh015** [comment]
@sbernier1 Are you using a Sony Android TV? If so, there's a known issue in Moonlight with HDR not working correctly right now due to a limitation of game mode on that platform.

**Comment by dom191984** [comment]
I have this issue on my sony tv and wanted to know how do I remove the moonlight_hdr_launcher from my pc. I want to play mass effect andromeda and now it is broken and the image is the steam os image and not mass effect. I can't see in the instructions how to uninstall?

**Comment by lyckantropen** [comment]
@dom191984 Hi, to remove the launcher delete the folder `C:\Program Files\moonlight_hdr_launcher` and run "Scan Now" in the "Games" settings category in GeForce Experience. It may be necessary to reboot for it to take full effect. In case you're still seeing it, go to `<user folder>\AppData\Local\NVIDIA\NvBackend\StreamingAssetsData\` and look for a subfolder that contains `mass_effect_andromeda` and remove it. It has write-protection enabled so you may need to disable it in the properties.

**Comment by dom191984** [comment]
It has write-protection enabled so you may need to disable it in the properties

How do I do this, sorry can't find an option?

**Comment by lyckantropen** [comment]
@dom191984 Right-click the folder and open Properties. On the first panel make sure that "Read only" is unchecked. On the second panel, select your user in the first list and make sure "Full control" or "Modification" and "Write" are checked in the "Allow" column.

**Comment by dom191984** [comment]
Ok I am the admin but it won't let me apply if I uncheck the read only. I have full control but cannot disable read only, even as admin

![image](https://user-images.githubusercontent.com/42463973/119466709-cffbb880-bd3c-11eb-901d-5b497ae93001.png)

**Comment by lyckantropen** [comment]
@dom191984 Ok, try this. Open a PowerShell terminal as Administrator, `cd` into the folder above and run the command:

```powershell
Set-ItemProperty -Path mass_effect_andromeda -Name IsReadOnly -Value $false
```

**Comment by dom191984** [comment]
![image](https://user-images.githubusercontent.com/42463973/119468050-02f27c00-bd3e-11eb-915d-446fefcd5183.png)

**Comment by lyckantropen** [comment]
@dom191984 Oh, ok. The property [cannot in fact be set or changed for folders](https://answers.microsoft.com/en-us/windows/forum/windows_10-files/cannot-remove-read-only-attribute-windows-10-tried/ac8504c6-9951-4d21-b386-3f33344ff771). So it is irrelevant. You just need to change them for the files. So either substitute `mass_effect_andromeda/*` or just select the files in Explorer and change the access there.

**Comment by dom191984** [comment]
Cool, that worked

Just had to change it from file level. Cheers for your help

**Comment by lyckantropen** [comment]
@dom191984 Sorry you had problems. I will in fact work on an uninstaller to help people avoid such issues.

**Comment by dom191984** [comment]
No worries, I appreciate your assistance and speedy responses.

**Comment by dom191984** [comment]
@lyckantropen For some reason now Mass Effect Andromeda is not finding the folder number etc in the 
\NVIDIA\NvBackend\StreamingAssetsData
Even scanning for games in Nvidia Geforce Experience does not restore where the deleted files were

It just creates an empty Mass Effect Andromeda folder. I can't even remember what the folder number was to create one
Any help would be much appreciated

**Comment by lyckantropen** [comment]
@dom191984  I do not know of any other places where GeForce Experience stores its cache. I was typically able to revive the entry by alternating "Scan Now", force-quitting every nvidia-related process and restarting GFE or rebooting. Other than that I doubt much can be done beyond removing GFE completely and re-installing it :( It's completely related to GFE and not the game - of that I'm sure. GFE looks for the executable `MassEffectAndromeda.exe`, that's the only process involved.

**Comment by lyckantropen** [comment]
@dom191984 In `...\NVIDIA\NvBackend\StreamingAssetsData` there are also `.json` files where there might still be entries pointing to the old folders, you can try editing them manually.
